%% \VignetteIndexEntry{Bioconductor LaTeX Style}

\documentclass{article}

<<style, echo=FALSE, results=tex>>=
BiocStyle::latex()
@ 

\title{\Bioconductor{} \LaTeX{} Style}
\author{Martin Morgan, Andrzej Ole\'s, Wolfgang Huber}
\date{Revised: 1 July, 2013}

\begin{document}

\maketitle

\tableofcontents

\section{Use}

Add the following to your package \texttt{DESCRIPTION}:
\begin{verbatim}
    Suggests: BiocStyle
\end{verbatim}
Add this code chunk to the preamble of each vignette:
\begin{verbatim}
    <<style, echo=FALSE, results=tex>>=
    BiocStyle::latex()
    @ 
\end{verbatim}

\section{Mark-up}

\texttt{Bioconductor.sty} defines the following commands.
%% 
Software:
\begin{itemize}
\item \verb+\R{}+ and \verb+\Bioconductor{}+ to reference \R{}
  software and the \Bioconductor{} project.
\item \verb+\software{GATK}+ to reference third-party software, e.g.,
  \software{GATK}.
\end{itemize}
%% 
Packages:
\begin{itemize}
\item \verb+\Biocpkg{IRanges}+ for \Bioconductor{} software packages, including
  a link to the release version landing page, \Biocpkg{IRanges}.
\item \verb+\Biocannopkg{org.Hs.eg.db}+ for \Bioconductor{} annotation
  packages, including a link to the release version landing page,
  \Biocannopkg{org.Hs.eg.db}.
\item \verb+\Biocexptpkg{parathyroidSE}+ for \Bioconductor{}
  experiment data packages, including a link to the release version
  landing page, \Biocexptpkg{parathyroidSE}.
\item \verb+\Rpkg{data.table}+ for \R{} packages available on CRAN,
  including a link to the FHCRC CRAN mirror landing page,
  \Rpkg{data.table}.
\item \verb+\Rpackage{MyPkg}+ for \R{} packages that are \emph{not}
  available on \Bioconductor{} or CRAN.
\end{itemize}
%% 
Code:
\begin{itemize}
\item \verb+\Rfunction{findOverlaps}+ for functions
  \Rfunction{findOverlaps}.
\item \verb+\Robject{olaps}+ for variables \Robject{olaps}.
\item \verb+\Rclass{GRanges}+ when refering to a formal class
  \Rclass{GRanges}.
\end{itemize}
%% 
Communication:
\begin{itemize}
\item \verb+\comment{comment to the user}+ communicates a
  \comment{comment to the user}.
\item \verb+\warning{common pitfalls}+ signals \warning{common
    pitfalls}.
\item \verb+\fixme{incomplete functionality}+ provides an indication
  of \fixme{incomplete functionality}.
\end{itemize}
%% 
Environments:
\begin{packeditemize}
\item Use \verb+packeditemize+ for itemizations\ldots
\item with tighter item spacing
\end{packeditemize}
\begin{packedenumerate}
\item Use \verb+packedenumerate+ for enumerations\ldots
\item \ldots with tighter item spacing
\end{packedenumerate}
\begin{packeddescription}
\item[first] Use \verb+packeddescription+ for descriptions\ldots
\item[second] \ldots with tighter item spacing
\end{packeddescription}

\section{Sectioning: this is a section}

Use \verb+\tableofcontents+ for hyperlinked table of contents.

\subsection{This is a subsection}

\subsubsection{This is a subsubsection}

\end{document}
